# application-qa.yml (Testing/QA)
spring:
  config:
    activate:
      on-profile: qa

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecommerce_qa}
    username: ${DATABASE_USERNAME:ecommerce_user}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.ecommerce: INFO