spring:
  application:
    name: spring-boot-ecommerce
  
  profiles:
    active: dev
  
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

# Configuración de JWT
app:
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds

# Configuración de logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    com.ecommerce: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method